# Autogenerated using db-gen
# Changes to this file will be lost on next generation

defmodule Database.DbContext do
  @moduledoc """
  Database context module for calling stored procedures and functions.
  This code has been auto-generated - changes to this file will be lost on next generation.
  """

  require Logger
  alias Database.{Models, Processors}
  import Ecto.Query

  @repo PureAdminIcons.Repo

  @doc """
  Execute a parameterized SQL query
  """
  def query(sql, params, opts \\ []) do
    @repo.query(sql, params, opts)
  end


  @doc """
  Calls database function const.get_categories
  
  Returns: {:ok, [%Models.ConstGetCategoriesModel{}]} | {:error, any()}
  
  """
  @spec const_get_categories(String.t() | :eg_value_not_provided, keyword()) :: {:ok, [%Models.ConstGetCategoriesModel{}]} | {:error, any()}
  def const_get_categories(display_language_code \\ :eg_value_not_provided, query_opts \\ []) do
    Logger.debug("Calling database routine", routine_name: "get_categories")

    sql_params_str =
      [
        {"_display_language_code", display_language_code}
      ]
      |> Enum.filter(fn {_name, value} -> value != :eg_value_not_provided end)
      |> Enum.with_index(1)
      |> Enum.map(fn {_tuple, index} -> "$#{index}" end)
      |> Enum.join(", ")

    sql_query_params =
      [
        display_language_code
      ]
      |> Enum.filter(fn value -> value != :eg_value_not_provided end)

    query(
      "select * from const.get_categories(#{sql_params_str})",
      sql_query_params,
      query_opts
    )
    
    |> Processors.ConstGetCategoriesProcessor.parse_result()
    
  end


  @doc """
  Calls database function const.get_icon_sets
  
  Returns: {:ok, [%Models.ConstGetIconSetsModel{}]} | {:error, any()}
  
  """
  @spec const_get_icon_sets(String.t() | :eg_value_not_provided, integer() | :eg_value_not_provided, keyword()) :: {:ok, [%Models.ConstGetIconSetsModel{}]} | {:error, any()}
  def const_get_icon_sets(display_language_code \\ :eg_value_not_provided, tenant_id \\ :eg_value_not_provided, query_opts \\ []) do
    Logger.debug("Calling database routine", routine_name: "get_icon_sets")

    sql_params_str =
      [
        {"_display_language_code", display_language_code},
        {"_tenant_id", tenant_id}
      ]
      |> Enum.filter(fn {_name, value} -> value != :eg_value_not_provided end)
      |> Enum.with_index(1)
      |> Enum.map(fn {_tuple, index} -> "$#{index}" end)
      |> Enum.join(", ")

    sql_query_params =
      [
        display_language_code,
        tenant_id
      ]
      |> Enum.filter(fn value -> value != :eg_value_not_provided end)

    query(
      "select * from const.get_icon_sets(#{sql_params_str})",
      sql_query_params,
      query_opts
    )
    
    |> Processors.ConstGetIconSetsProcessor.parse_result()
    
  end


  @doc """
  Calls database function public.create_job_run
  
  Returns: {:ok, [%Models.CreateJobRunModel{}]} | {:error, any()}
  
  """
  @spec create_job_run(String.t(), String.t(), map() | list() | :eg_value_not_provided, keyword()) :: {:ok, [%Models.CreateJobRunModel{}]} | {:error, any()}
  def create_job_run(run_by, job_run_type_code, job_data \\ :eg_value_not_provided, query_opts \\ []) do
    Logger.debug("Calling database routine", routine_name: "create_job_run")

    sql_params_str =
      [
        {"_run_by", run_by},
        {"_job_run_type_code", job_run_type_code},
        {"_job_data", job_data}
      ]
      |> Enum.filter(fn {_name, value} -> value != :eg_value_not_provided end)
      |> Enum.with_index(1)
      |> Enum.map(fn {_tuple, index} -> "$#{index}" end)
      |> Enum.join(", ")

    sql_query_params =
      [
        run_by,
        job_run_type_code,
        job_data
      ]
      |> Enum.filter(fn value -> value != :eg_value_not_provided end)

    query(
      "select * from public.create_job_run(#{sql_params_str})",
      sql_query_params,
      query_opts
    )
    
    |> Processors.CreateJobRunProcessor.parse_result()
    
  end


  @doc """
  Calls database function public.get_group_translations
  
  Returns: {:ok, [%Models.GetGroupTranslationsModel{}]} | {:error, any()}
  
  """
  @spec get_group_translations(String.t(), String.t(), String.t() | :eg_value_not_provided, integer() | :eg_value_not_provided, keyword()) :: {:ok, [%Models.GetGroupTranslationsModel{}]} | {:error, any()}
  def get_group_translations(language_code, data_group, context \\ :eg_value_not_provided, tenant_id \\ :eg_value_not_provided, query_opts \\ []) do
    Logger.debug("Calling database routine", routine_name: "get_group_translations")

    sql_params_str =
      [
        {"_language_code", language_code},
        {"_data_group", data_group},
        {"_context", context},
        {"_tenant_id", tenant_id}
      ]
      |> Enum.filter(fn {_name, value} -> value != :eg_value_not_provided end)
      |> Enum.with_index(1)
      |> Enum.map(fn {_tuple, index} -> "$#{index}" end)
      |> Enum.join(", ")

    sql_query_params =
      [
        language_code,
        data_group,
        context,
        tenant_id
      ]
      |> Enum.filter(fn value -> value != :eg_value_not_provided end)

    query(
      "select * from public.get_group_translations(#{sql_params_str})",
      sql_query_params,
      query_opts
    )
    
    |> Processors.GetGroupTranslationsProcessor.parse_result()
    
  end


  @doc """
  Calls database function public.get_icon_by_filename
  
  Returns: {:ok, [%Models.GetIconByFilenameModel{}]} | {:error, any()}
  
  """
  @spec get_icon_by_filename(String.t(), String.t(), String.t(), keyword()) :: {:ok, [%Models.GetIconByFilenameModel{}]} | {:error, any()}
  def get_icon_by_filename(icon_set_code, style_code, filename, query_opts \\ []) do
    Logger.debug("Calling database routine", routine_name: "get_icon_by_filename")

    sql_params_str =
      [
        {"_icon_set_code", icon_set_code},
        {"_style_code", style_code},
        {"_filename", filename}
      ]
      |> Enum.filter(fn {_name, value} -> value != :eg_value_not_provided end)
      |> Enum.with_index(1)
      |> Enum.map(fn {_tuple, index} -> "$#{index}" end)
      |> Enum.join(", ")

    sql_query_params =
      [
        icon_set_code,
        style_code,
        filename
      ]
      |> Enum.filter(fn value -> value != :eg_value_not_provided end)

    query(
      "select * from public.get_icon_by_filename(#{sql_params_str})",
      sql_query_params,
      query_opts
    )
    
    |> Processors.GetIconByFilenameProcessor.parse_result()
    
  end


  @doc """
  Calls database function public.get_icon_count
  
  Returns: {:ok, [%Models.GetIconCountModel{}]} | {:error, any()}
  
  """
  @spec get_icon_count(String.t() | :eg_value_not_provided, keyword()) :: {:ok, [%Models.GetIconCountModel{}]} | {:error, any()}
  def get_icon_count(icon_set_code \\ :eg_value_not_provided, query_opts \\ []) do
    Logger.debug("Calling database routine", routine_name: "get_icon_count")

    sql_params_str =
      [
        {"_icon_set_code", icon_set_code}
      ]
      |> Enum.filter(fn {_name, value} -> value != :eg_value_not_provided end)
      |> Enum.with_index(1)
      |> Enum.map(fn {_tuple, index} -> "$#{index}" end)
      |> Enum.join(", ")

    sql_query_params =
      [
        icon_set_code
      ]
      |> Enum.filter(fn value -> value != :eg_value_not_provided end)

    query(
      "select * from public.get_icon_count(#{sql_params_str})",
      sql_query_params,
      query_opts
    )
    
    |> Processors.GetIconCountProcessor.parse_result()
    
  end


  @doc """
  Calls database function public.get_icon_counts_by_set
  
  Returns: {:ok, [%Models.GetIconCountsBySetModel{}]} | {:error, any()}
  
  """
  @spec get_icon_counts_by_set(keyword()) :: {:ok, [%Models.GetIconCountsBySetModel{}]} | {:error, any()}
  def get_icon_counts_by_set(query_opts \\ []) do
    Logger.debug("Calling database routine", routine_name: "get_icon_counts_by_set")

    sql_params_str =
      [

      ]
      |> Enum.filter(fn {_name, value} -> value != :eg_value_not_provided end)
      |> Enum.with_index(1)
      |> Enum.map(fn {_tuple, index} -> "$#{index}" end)
      |> Enum.join(", ")

    sql_query_params =
      [

      ]
      |> Enum.filter(fn value -> value != :eg_value_not_provided end)

    query(
      "select * from public.get_icon_counts_by_set(#{sql_params_str})",
      sql_query_params,
      query_opts
    )
    
    |> Processors.GetIconCountsBySetProcessor.parse_result()
    
  end


  @doc """
  Calls database function public.get_icon_detail
  
  Returns: {:ok, [%Models.GetIconDetailModel{}]} | {:error, any()}
  
  """
  @spec get_icon_detail(integer(), keyword()) :: {:ok, [%Models.GetIconDetailModel{}]} | {:error, any()}
  def get_icon_detail(icon_id, query_opts \\ []) do
    Logger.debug("Calling database routine", routine_name: "get_icon_detail")

    sql_params_str =
      [
        {"_icon_id", icon_id}
      ]
      |> Enum.filter(fn {_name, value} -> value != :eg_value_not_provided end)
      |> Enum.with_index(1)
      |> Enum.map(fn {_tuple, index} -> "$#{index}" end)
      |> Enum.join(", ")

    sql_query_params =
      [
        icon_id
      ]
      |> Enum.filter(fn value -> value != :eg_value_not_provided end)

    query(
      "select * from public.get_icon_detail(#{sql_params_str})",
      sql_query_params,
      query_opts
    )
    
    |> Processors.GetIconDetailProcessor.parse_result()
    
  end


  @doc """
  Calls database function public.get_icon_details_by_keys
  
  Returns: {:ok, [%Models.GetIconDetailsByKeysModel{}]} | {:error, any()}
  
  """
  @spec get_icon_details_by_keys(map() | list(), keyword()) :: {:ok, [%Models.GetIconDetailsByKeysModel{}]} | {:error, any()}
  def get_icon_details_by_keys(pairs, query_opts \\ []) do
    Logger.debug("Calling database routine", routine_name: "get_icon_details_by_keys")

    sql_params_str =
      [
        {"_pairs", pairs}
      ]
      |> Enum.filter(fn {_name, value} -> value != :eg_value_not_provided end)
      |> Enum.with_index(1)
      |> Enum.map(fn {_tuple, index} -> "$#{index}" end)
      |> Enum.join(", ")

    sql_query_params =
      [
        pairs
      ]
      |> Enum.filter(fn value -> value != :eg_value_not_provided end)

    query(
      "select * from public.get_icon_details_by_keys(#{sql_params_str})",
      sql_query_params,
      query_opts
    )
    
    |> Processors.GetIconDetailsByKeysProcessor.parse_result()
    
  end


  @doc """
  Calls database function public.get_icon_metrics
  
  Returns: {:ok, [%Models.GetIconMetricsModel{}]} | {:error, any()}
  
  """
  @spec get_icon_metrics(integer(), keyword()) :: {:ok, [%Models.GetIconMetricsModel{}]} | {:error, any()}
  def get_icon_metrics(icon_id, query_opts \\ []) do
    Logger.debug("Calling database routine", routine_name: "get_icon_metrics")

    sql_params_str =
      [
        {"_icon_id", icon_id}
      ]
      |> Enum.filter(fn {_name, value} -> value != :eg_value_not_provided end)
      |> Enum.with_index(1)
      |> Enum.map(fn {_tuple, index} -> "$#{index}" end)
      |> Enum.join(", ")

    sql_query_params =
      [
        icon_id
      ]
      |> Enum.filter(fn value -> value != :eg_value_not_provided end)

    query(
      "select * from public.get_icon_metrics(#{sql_params_str})",
      sql_query_params,
      query_opts
    )
    
    |> Processors.GetIconMetricsProcessor.parse_result()
    
  end


  @doc """
  Calls database function public.get_icon_primary_name
  
  Returns: {:ok, [%Models.GetIconPrimaryNameModel{}]} | {:error, any()}
  
  """
  @spec get_icon_primary_name(integer(), keyword()) :: {:ok, [%Models.GetIconPrimaryNameModel{}]} | {:error, any()}
  def get_icon_primary_name(icon_id, query_opts \\ []) do
    Logger.debug("Calling database routine", routine_name: "get_icon_primary_name")

    sql_params_str =
      [
        {"_icon_id", icon_id}
      ]
      |> Enum.filter(fn {_name, value} -> value != :eg_value_not_provided end)
      |> Enum.with_index(1)
      |> Enum.map(fn {_tuple, index} -> "$#{index}" end)
      |> Enum.join(", ")

    sql_query_params =
      [
        icon_id
      ]
      |> Enum.filter(fn value -> value != :eg_value_not_provided end)

    query(
      "select * from public.get_icon_primary_name(#{sql_params_str})",
      sql_query_params,
      query_opts
    )
    
    |> Processors.GetIconPrimaryNameProcessor.parse_result()
    
  end


  @doc """
  Calls database function public.get_icon_sets
  
  Returns: {:ok, [%Models.GetIconSetsModel{}]} | {:error, any()}
  
  """
  @spec get_icon_sets(String.t() | :eg_value_not_provided, integer() | :eg_value_not_provided, keyword()) :: {:ok, [%Models.GetIconSetsModel{}]} | {:error, any()}
  def get_icon_sets(display_language_code \\ :eg_value_not_provided, tenant_id \\ :eg_value_not_provided, query_opts \\ []) do
    Logger.debug("Calling database routine", routine_name: "get_icon_sets")

    sql_params_str =
      [
        {"_display_language_code", display_language_code},
        {"_tenant_id", tenant_id}
      ]
      |> Enum.filter(fn {_name, value} -> value != :eg_value_not_provided end)
      |> Enum.with_index(1)
      |> Enum.map(fn {_tuple, index} -> "$#{index}" end)
      |> Enum.join(", ")

    sql_query_params =
      [
        display_language_code,
        tenant_id
      ]
      |> Enum.filter(fn value -> value != :eg_value_not_provided end)

    query(
      "select * from public.get_icon_sets(#{sql_params_str})",
      sql_query_params,
      query_opts
    )
    
    |> Processors.GetIconSetsProcessor.parse_result()
    
  end


  @doc """
  Calls database function public.get_last_sync
  
  Returns: {:ok, [%Models.GetLastSyncModel{}]} | {:error, any()}
  
  """
  @spec get_last_sync(String.t() | :eg_value_not_provided, keyword()) :: {:ok, [%Models.GetLastSyncModel{}]} | {:error, any()}
  def get_last_sync(icon_set_code \\ :eg_value_not_provided, query_opts \\ []) do
    Logger.debug("Calling database routine", routine_name: "get_last_sync")

    sql_params_str =
      [
        {"_icon_set_code", icon_set_code}
      ]
      |> Enum.filter(fn {_name, value} -> value != :eg_value_not_provided end)
      |> Enum.with_index(1)
      |> Enum.map(fn {_tuple, index} -> "$#{index}" end)
      |> Enum.join(", ")

    sql_query_params =
      [
        icon_set_code
      ]
      |> Enum.filter(fn value -> value != :eg_value_not_provided end)

    query(
      "select * from public.get_last_sync(#{sql_params_str})",
      sql_query_params,
      query_opts
    )
    
    |> Processors.GetLastSyncProcessor.parse_result()
    
  end


  @doc """
  Calls database function public.get_popular_icons
  
  Returns: {:ok, [%Models.GetPopularIconsModel{}]} | {:error, any()}
  
  """
  @spec get_popular_icons(String.t() | :eg_value_not_provided, String.t() | :eg_value_not_provided, String.t() | :eg_value_not_provided, String.t() | :eg_value_not_provided, String.t() | :eg_value_not_provided, integer() | :eg_value_not_provided, keyword()) :: {:ok, [%Models.GetPopularIconsModel{}]} | {:error, any()}
  def get_popular_icons(period_code \\ :eg_value_not_provided, action_code \\ :eg_value_not_provided, icon_set_code \\ :eg_value_not_provided, style_code \\ :eg_value_not_provided, source_code \\ :eg_value_not_provided, limit \\ :eg_value_not_provided, query_opts \\ []) do
    Logger.debug("Calling database routine", routine_name: "get_popular_icons")

    sql_params_str =
      [
        {"_period_code", period_code},
        {"_action_code", action_code},
        {"_icon_set_code", icon_set_code},
        {"_style_code", style_code},
        {"_source_code", source_code},
        {"_limit", limit}
      ]
      |> Enum.filter(fn {_name, value} -> value != :eg_value_not_provided end)
      |> Enum.with_index(1)
      |> Enum.map(fn {_tuple, index} -> "$#{index}" end)
      |> Enum.join(", ")

    sql_query_params =
      [
        period_code,
        action_code,
        icon_set_code,
        style_code,
        source_code,
        limit
      ]
      |> Enum.filter(fn value -> value != :eg_value_not_provided end)

    query(
      "select * from public.get_popular_icons(#{sql_params_str})",
      sql_query_params,
      query_opts
    )
    
    |> Processors.GetPopularIconsProcessor.parse_result()
    
  end


  @doc """
  Calls database function public.get_stats_overview
  
  Returns: {:ok, [%Models.GetStatsOverviewModel{}]} | {:error, any()}
  
  """
  @spec get_stats_overview(keyword()) :: {:ok, [%Models.GetStatsOverviewModel{}]} | {:error, any()}
  def get_stats_overview(query_opts \\ []) do
    Logger.debug("Calling database routine", routine_name: "get_stats_overview")

    sql_params_str =
      [

      ]
      |> Enum.filter(fn {_name, value} -> value != :eg_value_not_provided end)
      |> Enum.with_index(1)
      |> Enum.map(fn {_tuple, index} -> "$#{index}" end)
      |> Enum.join(", ")

    sql_query_params =
      [

      ]
      |> Enum.filter(fn value -> value != :eg_value_not_provided end)

    query(
      "select * from public.get_stats_overview(#{sql_params_str})",
      sql_query_params,
      query_opts
    )
    
    |> Processors.GetStatsOverviewProcessor.parse_result()
    
  end


  @doc """
  Calls database procedure public.refresh_icon_metrics_cube
  
  Returns: {:ok, any()} | {:error, any()}
  
  """
  @spec refresh_icon_metrics_cube(keyword()) :: {:ok, any()} | {:error, any()}
  def refresh_icon_metrics_cube(query_opts \\ []) do
    Logger.debug("Calling database routine", routine_name: "refresh_icon_metrics_cube")

    sql_params_str =
      [

      ]
      |> Enum.filter(fn {_name, value} -> value != :eg_value_not_provided end)
      |> Enum.with_index(1)
      |> Enum.map(fn {_tuple, index} -> "$#{index}" end)
      |> Enum.join(", ")

    sql_query_params =
      [

      ]
      |> Enum.filter(fn value -> value != :eg_value_not_provided end)

    query(
      "call public.refresh_icon_metrics_cube(#{sql_params_str})",
      sql_query_params,
      query_opts
    )
    
  end


  @doc """
  Calls database function public.search_icons
  
  Returns: {:ok, [%Models.SearchIconsModel{}]} | {:error, any()}
  
  """
  @spec search_icons(String.t() | :eg_value_not_provided, integer() | :eg_value_not_provided, integer() | :eg_value_not_provided, keyword()) :: {:ok, [%Models.SearchIconsModel{}]} | {:error, any()}
  def search_icons(search_criteria \\ :eg_value_not_provided, page \\ :eg_value_not_provided, page_size \\ :eg_value_not_provided, query_opts \\ []) do
    Logger.debug("Calling database routine", routine_name: "search_icons")

    sql_params_str =
      [
        {"_search_criteria", search_criteria},
        {"_page", page},
        {"_page_size", page_size}
      ]
      |> Enum.filter(fn {_name, value} -> value != :eg_value_not_provided end)
      |> Enum.with_index(1)
      |> Enum.map(fn {_tuple, index} -> "$#{index}" end)
      |> Enum.join(", ")

    sql_query_params =
      [
        search_criteria,
        page,
        page_size
      ]
      |> Enum.filter(fn value -> value != :eg_value_not_provided end)

    query(
      "select * from public.search_icons(#{sql_params_str})",
      sql_query_params,
      query_opts
    )
    
    |> Processors.SearchIconsProcessor.parse_result()
    
  end


  @doc """
  Calls database procedure public.track_icon_action
  
  Returns: {:ok, any()} | {:error, any()}
  
  """
  @spec track_icon_action(integer(), String.t(), String.t(), integer() | :eg_value_not_provided, String.t() | :eg_value_not_provided, String.t() | :eg_value_not_provided, keyword()) :: {:ok, any()} | {:error, any()}
  def track_icon_action(icon_id, action_code, source_code, size \\ :eg_value_not_provided, surface_code \\ :eg_value_not_provided, format_code \\ :eg_value_not_provided, query_opts \\ []) do
    Logger.debug("Calling database routine", routine_name: "track_icon_action")

    sql_params_str =
      [
        {"_icon_id", icon_id},
        {"_action_code", action_code},
        {"_source_code", source_code},
        {"_size", size},
        {"_surface_code", surface_code},
        {"_format_code", format_code}
      ]
      |> Enum.filter(fn {_name, value} -> value != :eg_value_not_provided end)
      |> Enum.with_index(1)
      |> Enum.map(fn {_tuple, index} -> "$#{index}" end)
      |> Enum.join(", ")

    sql_query_params =
      [
        icon_id,
        action_code,
        source_code,
        size,
        surface_code,
        format_code
      ]
      |> Enum.filter(fn value -> value != :eg_value_not_provided end)

    query(
      "call public.track_icon_action(#{sql_params_str})",
      sql_query_params,
      query_opts
    )
    
  end


  @doc """
  Calls database procedure public.track_search
  
  Returns: {:ok, any()} | {:error, any()}
  
  """
  @spec track_search(String.t(), integer(), String.t(), integer() | :eg_value_not_provided, String.t() | :eg_value_not_provided, String.t() | :eg_value_not_provided, keyword()) :: {:ok, any()} | {:error, any()}
  def track_search(query, result_count, source_code, size \\ :eg_value_not_provided, style \\ :eg_value_not_provided, icon_set_code \\ :eg_value_not_provided, query_opts \\ []) do
    Logger.debug("Calling database routine", routine_name: "track_search")

    sql_params_str =
      [
        {"_query", query},
        {"_result_count", result_count},
        {"_source_code", source_code},
        {"_size", size},
        {"_style", style},
        {"_icon_set_code", icon_set_code}
      ]
      |> Enum.filter(fn {_name, value} -> value != :eg_value_not_provided end)
      |> Enum.with_index(1)
      |> Enum.map(fn {_tuple, index} -> "$#{index}" end)
      |> Enum.join(", ")

    sql_query_params =
      [
        query,
        result_count,
        source_code,
        size,
        style,
        icon_set_code
      ]
      |> Enum.filter(fn value -> value != :eg_value_not_provided end)

    query(
      "call public.track_search(#{sql_params_str})",
      sql_query_params,
      query_opts
    )
    
  end


  @doc """
  Calls database function public.update_job_run
  
  Returns: {:ok, any()} | {:error, any()}
  
  """
  @spec update_job_run(integer(), String.t(), map() | list() | :eg_value_not_provided, map() | list() | :eg_value_not_provided, keyword()) :: {:ok, any()} | {:error, any()}
  def update_job_run(job_run_id, status_code, success_data \\ :eg_value_not_provided, fail_data \\ :eg_value_not_provided, query_opts \\ []) do
    Logger.debug("Calling database routine", routine_name: "update_job_run")

    sql_params_str =
      [
        {"_job_run_id", job_run_id},
        {"_status_code", status_code},
        {"_success_data", success_data},
        {"_fail_data", fail_data}
      ]
      |> Enum.filter(fn {_name, value} -> value != :eg_value_not_provided end)
      |> Enum.with_index(1)
      |> Enum.map(fn {_tuple, index} -> "$#{index}" end)
      |> Enum.join(", ")

    sql_query_params =
      [
        job_run_id,
        status_code,
        success_data,
        fail_data
      ]
      |> Enum.filter(fn value -> value != :eg_value_not_provided end)

    query(
      "call public.update_job_run(#{sql_params_str})",
      sql_query_params,
      query_opts
    )
    
  end


  @doc """
  Calls database function stage.process_icon_import
  
  Returns: {:ok, [%Models.StageProcessIconImportModel{}]} | {:error, any()}
  
  """
  @spec stage_process_icon_import(String.t(), integer(), keyword()) :: {:ok, [%Models.StageProcessIconImportModel{}]} | {:error, any()}
  def stage_process_icon_import(run_by, job_run_id, query_opts \\ []) do
    Logger.debug("Calling database routine", routine_name: "process_icon_import")

    sql_params_str =
      [
        {"_run_by", run_by},
        {"_job_run_id", job_run_id}
      ]
      |> Enum.filter(fn {_name, value} -> value != :eg_value_not_provided end)
      |> Enum.with_index(1)
      |> Enum.map(fn {_tuple, index} -> "$#{index}" end)
      |> Enum.join(", ")

    sql_query_params =
      [
        run_by,
        job_run_id
      ]
      |> Enum.filter(fn value -> value != :eg_value_not_provided end)

    query(
      "select * from stage.process_icon_import(#{sql_params_str})",
      sql_query_params,
      query_opts
    )
    
    |> Processors.StageProcessIconImportProcessor.parse_result()
    
  end


end
