defmodule PureAdminIconsWeb.Endpoint do
  use Phoenix.Endpoint, otp_app: :pure_admin_icons

  # The session will be stored in the cookie and signed,
  # this means its contents can be read but not tampered with.
  # Set :encryption_salt if you would also like to encrypt it.
  @session_options [
    store: :cookie,
    key: "_pure_admin_icons_key",
    signing_salt: "sQ9BTeGO",
    same_site: "Lax"
  ]

  # We're always behind Traefik in prod, which terminates TLS and forwards
  # over HTTP. Trust its X-Forwarded-* headers so Phoenix sees the right
  # scheme/host/port for URL generation without redirecting.
  plug Plug.RewriteOn, [:x_forwarded_host, :x_forwarded_port, :x_forwarded_proto]

  # peer_data = direct socket peer (the Traefik hop in prod); x_headers carries
  # x-forwarded-for so audit sessions can record the real client IP.
  socket "/live", Phoenix.LiveView.Socket,
    websocket: [connect_info: [:peer_data, :x_headers, session: @session_options]],
    longpoll: [connect_info: [:peer_data, :x_headers, session: @session_options]]

  # Serve at "/" the static files from "priv/static" directory.
  #
  # When code reloading is disabled (e.g., in production),
  # the `gzip` option is enabled to serve compressed
  # static files generated by running `phx.digest`.
  plug Plug.Static,
    at: "/",
    from: :pure_admin_icons,
    gzip: not code_reloading?,
    only: PureAdminIconsWeb.static_paths(),
    raise_on_missing_only: code_reloading?

  # Code reloading can be explicitly enabled under the
  # :code_reloader configuration of your endpoint.
  if code_reloading? do
    socket "/phoenix/live_reload/socket", Phoenix.LiveReloader.Socket
    plug Phoenix.LiveReloader
    plug Phoenix.CodeReloader
  end

  plug Plug.RequestId
  plug Plug.Telemetry, event_prefix: [:phoenix, :endpoint]

  plug Plug.Parsers,
    parsers: [:urlencoded, :multipart, :json],
    pass: ["*/*"],
    json_decoder: Phoenix.json_library()

  plug Plug.MethodOverride
  plug Plug.Head
  plug Plug.Session, @session_options

  # Stamp X-MCP-* version headers on responses. Unmatched /api/* paths route to
  # a fallback 404 so they carry the headers too. See the plug's docs.
  plug PureAdminIconsWeb.Plugs.McpVersionHeaders

  plug PureAdminIconsWeb.Router
end
