defmodule Mix.Tasks.Translations.Gen do
  @shortdoc "Regenerates upsert_frontend_translations.sql from @defaults"

  @moduledoc """
  Writes `../pure-admin-icons-database/upsert_frontend_translations.sql` from
  `PureAdminIcons.Translations.defaults/0`.

  The generated file is a stored-procedure wrapper around an idempotent upsert
  of every English default key. Run after adding or changing UI strings so the
  DB seed stays in sync with the in-source fallbacks.

  ## Usage

      mix translations.gen
      mix translations.gen --output=/some/other/path.sql

  After regenerating, apply with:

      psql -f ../pure-admin-icons-database/upsert_frontend_translations.sql

  Then drop the in-app cache in iex:

      PureAdminIcons.Translations.DbProvider.refresh()
  """

  use Mix.Task

  @default_output "../pure-admin-icons-database/upsert_frontend_translations.sql"

  @data_group "frontend"
  @context "text"
  @tenant_id 1
  @seed_user "create-script"

  # English is the baseline / fallback source (lives in @defaults in
  # translations.ex). Additional languages are read from JSON files in
  # priv/translations/<lang>.json; each file is a flat map `{"key": "value"}`.
  # Missing keys in a non-English file fall back to the English default at
  # runtime — no need to mirror every key.
  @base_locale "en"

  # Controls the domain order in the output. Unknown domains are appended
  # alphabetically after these. Keep in sync with @defaults layout.
  @domain_order ~w(
    common
    nav
    docsIndex
    iconSets
    iconSearch
    iconDetail
    apiDocs
    mcpDocs
    llmsDocs
    stats
    syncDiscrepancies
  )

  @domain_titles %{
    "common" => "Common",
    "nav" => "Navigation",
    "docsIndex" => "Docs index — /docs",
    "iconSets" => "Icon Sets — /docs/icon-sets",
    "iconSearch" => "Icon search — /",
    "iconDetail" => "Icon detail modal",
    "apiDocs" => "API docs — /docs/api",
    "mcpDocs" => "MCP docs — /docs/mcp",
    "llmsDocs" => "LLM docs — /docs/llms",
    "stats" => "Stats — /stats",
    "syncDiscrepancies" => "Sync discrepancies — /sync/discrepancies"
  }

  @impl Mix.Task
  def run(args) do
    Mix.Task.run("app.config")

    output =
      case OptionParser.parse(args, strict: [output: :string]) do
        {opts, _, _} -> Keyword.get(opts, :output, @default_output)
      end

    locales = load_locales()
    grouped_by_locale = Enum.map(locales, fn {lang, map} -> {lang, group_by_domain(map)} end)
    sql = render(grouped_by_locale)

    total = Enum.reduce(locales, 0, fn {_l, m}, acc -> acc + map_size(m) end)
    langs = locales |> Enum.map(fn {l, _} -> l end) |> Enum.join(",")

    File.write!(output, sql)
    Mix.shell().info("[translations.gen] Wrote #{total} rows (#{langs}) → #{output}")
  end

  # --- locale loading ---

  # Returns an ordered keyword list [{lang, %{key => value}}, …],
  # with the base locale first, then other languages sorted alphabetically.
  defp load_locales do
    english = PureAdminIcons.Translations.defaults()

    others =
      translations_dir()
      |> File.ls!()
      |> Enum.filter(&String.ends_with?(&1, ".json"))
      |> Enum.map(fn file ->
        lang = Path.rootname(file)
        map = File.read!(Path.join(translations_dir(), file)) |> Jason.decode!()
        {lang, map}
      end)
      |> Enum.reject(fn {lang, _} -> lang == @base_locale end)
      |> Enum.sort_by(fn {lang, _} -> lang end)

    [{@base_locale, english} | others]
  end

  defp translations_dir do
    Path.join([:code.priv_dir(:pure_admin_icons), "translations"])
  end

  # --- grouping ---

  defp group_by_domain(defaults) do
    grouped =
      defaults
      |> Enum.group_by(fn {key, _value} -> key |> String.split(".", parts: 2) |> hd() end)

    ordered_known =
      @domain_order
      |> Enum.map(fn domain -> {domain, Map.get(grouped, domain, [])} end)
      |> Enum.reject(fn {_, entries} -> entries == [] end)

    unknown =
      grouped
      |> Map.drop(@domain_order)
      |> Enum.sort_by(fn {domain, _} -> domain end)

    ordered_known ++ unknown
  end

  # --- rendering ---

  # groups_by_locale :: [{lang, [{domain, [{key, value}, ...]}, ...]}, ...]
  defp render(groups_by_locale) do
    {rendered, _} =
      Enum.map_reduce(groups_by_locale, true, fn {lang, groups}, first_overall? ->
        {text, first_overall_after?} = render_locale(lang, groups, first_overall?)
        {text, first_overall_after?}
      end)

    rows = Enum.join(rendered, "\n")

    """
    -- icons.pureadmin.io — frontend UI translations
    --
    -- GENERATED by `mix translations.gen` from PureAdminIcons.Translations.defaults/0.
    -- Do not hand-edit; regenerate from the Elixir source of truth.
    --
    -- Idempotent upsert: safe to re-run. After running, the SP refreshes
    -- mv_translation. In the app, also call
    -- `PureAdminIcons.Translations.DbProvider.refresh()` to drop the per-locale
    -- :persistent_term cache.

    CREATE OR REPLACE PROCEDURE internal.upsert_frontend_translations()
    LANGUAGE plpgsql
    AS
    $$
    DECLARE
      __seed_user text := '#{@seed_user}';
    BEGIN

      INSERT INTO public.translation
        (created_by, updated_by, language_code, data_group, data_object_code, context, value, tenant_id)
      VALUES
    #{rows}

      ON CONFLICT (language_code, data_group, data_object_code, context)
        WHERE data_object_code IS NOT NULL
        DO UPDATE SET
          value      = EXCLUDED.value,
          updated_at = now(),
          updated_by = EXCLUDED.updated_by;

      PERFORM internal.refresh_translation_cache();

    END;
    $$;

    CALL internal.upsert_frontend_translations();
    """
  end

  defp render_locale(lang, groups, first_overall?) do
    banner = "  -- ══════════════════════════ #{String.upcase(lang)} ══════════════════════════\n"

    {rendered, first_after?} =
      Enum.map_reduce(groups, first_overall?, fn {domain, entries}, first? ->
        render_group(lang, domain, entries, first?)
      end)

    {banner <> Enum.join(rendered, "\n"), first_after?}
  end

  defp render_group(lang, domain, entries, first_overall?) do
    title = Map.get(@domain_titles, domain, domain)
    sorted = Enum.sort_by(entries, fn {key, _} -> key end)

    header = "  -- #{title}\n"

    {body, first_after?} =
      Enum.map_reduce(sorted, first_overall?, fn {key, value}, first? ->
        {render_row(lang, key, value, first?: first?), false}
      end)

    {header <> Enum.join(body, "\n") <> "\n", first_after?}
  end

  defp render_row(lang, key, value, opts) do
    lead = if opts[:first?], do: "    ", else: "  , "
    v = sql_escape(value)

    key_col = pad(quoted(key), 57)
    ctx_col = quoted(@context)
    val_col = "'#{v}'"

    "#{lead}(__seed_user, __seed_user, '#{lang}', '#{@data_group}', #{key_col}, #{ctx_col}, #{val_col}, #{@tenant_id})"
  end

  defp quoted(s), do: "'" <> s <> "'"

  defp pad(s, min_width) do
    pad_len = max(0, min_width - String.length(s))
    s <> String.duplicate(" ", pad_len)
  end

  # Escape single quotes for PostgreSQL string literals.
  defp sql_escape(value) when is_binary(value) do
    String.replace(value, "'", "''")
  end
end
