import Config

# Icons storage
config :pure_admin_icons,
  icons_path: Path.expand("../.icons", __DIR__),
  use_icon_cache: true

# Configure your database
config :pure_admin_icons, PureAdminIcons.Repo,
  username: "pure_admin_icons",
  password: "pure_admin_icons",
  hostname: "localhost",
  database: "pure_admin_icons",
  show_sensitive_data_on_connection_error: true,
  pool_size: 10

config :pure_admin_icons, PureAdminIconsWeb.Endpoint,
  # Binding to loopback ipv4 address prevents access from other machines.
  # Change to `ip: {0, 0, 0, 0}` to allow access from other machines.
  http: [ip: {127, 0, 0, 1}, port: 4020],
  check_origin: false,
  code_reloader: true,
  debug_errors: true,
  secret_key_base: "jFEWuSg3/7pIcqFgwkIxWDOvYVlMjTrwzqoV8WW2qz2/bKUz8mXXdl35c1UR0oCX",
  watchers: [
    esbuild: {Esbuild, :install_and_run, [:pure_admin_icons, ~w(--sourcemap=inline --watch)]},
    tailwind: {Tailwind, :install_and_run, [:pure_admin_icons, ~w(--watch)]}
  ]

# ## SSL Support
#
# In order to use HTTPS in development, a self-signed
# certificate can be generated by running the following
# Mix task:
#
#     mix phx.gen.cert
#
# Run `mix help phx.gen.cert` for more information.
#
# The `http:` config above can be replaced with:
#
#     https: [
#       port: 4001,
#       cipher_suite: :strong,
#       keyfile: "priv/cert/selfsigned_key.pem",
#       certfile: "priv/cert/selfsigned.pem"
#     ],
#
# If desired, both `http:` and `https:` keys can be
# configured to run both http and https servers on
# different ports.

# Reload browser tabs when matching files change.
config :pure_admin_icons, PureAdminIconsWeb.Endpoint,
  live_reload: [
    web_console_logger: true,
    patterns: [
      # Static assets, except user uploads
      ~r"priv/static/(?!uploads/).*\.(js|css|png|jpeg|jpg|gif|svg)$",
      # Router, Controllers, LiveViews and LiveComponents
      ~r"lib/pure_admin_icons_web/router\.ex$",
      ~r"lib/pure_admin_icons_web/(controllers|live|components)/.*\.(ex|heex)$"
    ]
  ]

# Enable dev routes for dashboard and mailbox
config :pure_admin_icons, dev_routes: true

# Refresh metrics cube every 10s in dev (Quantum cron only goes to minutes)
config :pure_admin_icons, :metrics_cube_interval, 10_000

# Do not include metadata nor timestamps in development logs
config :logger, :default_formatter, format: "[$level] $message\n"

# Set a higher stacktrace during development. Avoid configuring such
# in production as building large stacktraces may be expensive.
config :phoenix, :stacktrace_depth, 20

# Initialize plugs at runtime for faster development compilation
config :phoenix, :plug_init_mode, :runtime

config :phoenix_live_view,
  # Include debug annotations and locations in rendered markup.
  # Changing this configuration will require mix clean and a full recompile.
  debug_heex_annotations: true,
  debug_attributes: true,
  # Enable helpful, but potentially expensive runtime checks
  enable_expensive_runtime_checks: true,
  # Silence the colocated-assets symlink warning on Windows (no admin symlink perms)
  colocated_assets: [disable_symlink_warning: true]
